### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by null15** [bonnie-dentinger/palia-fishing-guide#26]
How do I use? do I run "python.exe app.py"?

**Comment by null15** [comment]
Did pip install -r requirements.txt and got all the packages, but the website it serves me is just a blank one with einar on the right, no interactivity is possible

**Comment by bonbonbubbles** [comment]
This is not an app to run personally/locally. Please visit www.paliafishingguide.com ! It's where I'm hosting the webapp
